export const TRADERS = [
  'Prapor', 'Therapist', 'Fence', 'Skier', 'Peacekeeper', 
  'Mechanic', 'Ragman', 'Jaeger', 'Ref', 'Lightkeeper', 'BTR Driver'
];

export const TRADER_COLORS: Record<string, string> = {
  Prapor: 'border-red-600',
  Therapist: 'border-blue-400',
  Fence: 'border-gray-500',
  Skier: 'border-yellow-500',
  Peacekeeper: 'border-blue-600',
  Mechanic: 'border-purple-500',
  Ragman: 'border-emerald-500',
  Jaeger: 'border-green-700',
  Ref: 'border-red-400',
  Lightkeeper: 'border-orange-400',
  'BTR Driver': 'border-orange-600'
};

export const COLLECTOR_ITEMS = [
  "Old firesteel",
  "Antique axe",
  "Battered antique book",
  "#FireKlean gun lube",
  "Golden rooster figurine",
  "Silver Badge",
  "Deadlyslob's beard oil",
  "Golden 1GPhone smartphone",
  "Jar of DevilDog mayo",
  "Can of sprats",
  "Fake mustache",
  "Kotton beanie",
  "Raven figurine",
  "Pestily plague mask",
  "Shroud half-mask",
  "Can of Dr. Lupo's coffee beans",
  "42 Signature Blend English Tea",
  "Veritas guitar pick",
  "Armband (Evasion)",
  "Can of RatCola soda",
  "Loot Lord plushie",
  "WZ Wallet",
  "LVNDMARK's rat poison",
  "Smoke balaclava",
  "Missam forklift key",
  "Video cassette with the Cyborg Killer movie",
  "BakeEzy cook book",
  "JohnB Liquid DNB glasses",
  "Glorious E lightweight armored mask",
  "Baddie's red beard",
  "DRD body armor",
  "Gingy keychain",
  "Golden egg",
  "Press pass (issued for NoiceGuy)",
  "Axel parrot figurine",
  "BEAR Buddy plush toy",
  "Inseq gas pipe wrench",
  "Viibiin sneaker",
  "Tamatthi kunai knife replica",
  "Nut Sack balaclava",
  "Mazoni golden dumbbell",
  "Tigzresq splint",
  "Domontovich ushanka hat"
];